from matplotlib import pyplot;
from pylab import genfromtxt;  
mat0 = genfromtxt("../txt_data/asc_insort.txt");
mat1 = genfromtxt("../txt_data/asc_qsort.txt");
mat2 = genfromtxt("../txt_data/asc_msort.txt");
mat3 = genfromtxt("../txt_data/dsc_insort.txt");
mat4 = genfromtxt("../txt_data/dsc_qsort.txt");
mat5 = genfromtxt("../txt_data/dsc_msort.txt");
mat6 = genfromtxt("../txt_data/random_insort.txt");
mat7 = genfromtxt("../txt_data/random_qsort.txt");
mat8 = genfromtxt("../txt_data/random_msort.txt");
pyplot.plot(mat0[:,0], mat0[:,1], label = "insort (already sorted dataset)");
pyplot.plot(mat1[:,0], mat1[:,1], label = "qsort (already sorted dataset)");
pyplot.plot(mat2[:,0], mat2[:,1], label = "msort (already sorted dataset)");
pyplot.plot(mat3[:,0], mat3[:,1], label = "insort (reversed dataset)");
pyplot.plot(mat4[:,0], mat4[:,1], label = "qsort (reversed dataset)");
pyplot.plot(mat5[:,0], mat5[:,1], label = "msort (reversed dataset)");
pyplot.plot(mat6[:,0], mat6[:,1], label = "insort (random dataset)");
pyplot.plot(mat7[:,0], mat7[:,1], label = "qsort (random dataset)");
pyplot.plot(mat8[:,0], mat8[:,1], label = "msort (random dataset)");
pyplot.legend();
pyplot.title("Sorting with InsertionSort, QuickSort and MergeSort");
pyplot.xlabel("N");
pyplot.ylabel("t[ns]");
pyplot.show();